nml = {
    'rhoc':'theta_grid_parameters',
    'rmaj':'theta_grid_parameters',
    'r_geo':'theta_grid_parameters',
    'qinp':'theta_grid_parameters',
    'shat':'theta_grid_parameters',
    'shift':'theta_grid_parameters',
    'akappa':'theta_grid_parameters',
    'akappri':'theta_grid_parameters',
    'tri':'theta_grid_parameters',
    'tripri':'theta_grid_parameters',
    'ntheta':'theta_grid_parameters',
    'nperiod':'theta_grid_parameters',
    'beta':'parameters',
    'zeff':'parameters',
    'beta_prime_input':'theta_grid_eik_knobs',
    'ngauss':'le_grids_knobs',
    'negrid':'le_grids_knobs',
    'vcut':'le_grids_knobs',
    'g_exb':'dist_fn_knobs',
    'omprimfac':'dist_fn_knobs',
    'mach':'dist_fn_knobs',
    'save_for_restart':'gs2_diagnostics_knobs',
    'nwrite':'gs2_diagnostics_knobs',
    'phiinit':'init_g_knobs',
    'ny':'kt_grids_box_parameters',
    'nx':'kt_grids_box_parameters',
    'y0':'kt_grids_box_parameters',
    'jtwist':'kt_grids_box_parameters',
    'naky':'kt_grids_range_parameters',
    'aky_min':'kt_grids_range_parameters',
    'aky_max':'kt_grids_range_parameters',
    'ntheta0':'kt_grids_range_parameters',
    'theta0_min':'kt_grids_range_parameters',
    'theta0_max':'kt_grids_range_parameters',
    'fphi':'knobs',
    'fapar':'knobs',
    'fbpar':'knobs',
    'nstep':'knobs',
    'delt':'knobs',
    'nspec':'species_knobs',
    'dens':'species_parameters_{}',
    'densi':'species_parameters_1',
    'dense':'species_parameters_2',
    'densx':'species_parameters_3',
    'temp':'species_parameters_{}',
    'tempi':'species_parameters_1',
    'tempe':'species_parameters_2',
    'tempx':'species_parameters_3',
    'fprim':'species_parameters_{}',
    'fprimi':'species_parameters_1',
    'fprime':'species_parameters_2',
    'fprimx':'species_parameters_3',
    'tprim':'species_parameters_{}',
    'tprimi':'species_parameters_1',
    'tprime':'species_parameters_2',
    'tprimx':'species_parameters_3',
    'vnewk':'species_parameters_{}',
    'vnewki':'species_parameters_1',
    'vnewke':'species_parameters_2',
    'vnewkx':'species_parameters_3',
    'cfl':'nonlinear_terms_knobs',
}


altnml = {
    'shat':'theta_grid_eik_knobs'
}


altname = {
    'shat':'s_hat_input'
}

